Updated install doc of the minimum required macOS (#5833)
I have tested installing GMT versions 6.1.1, 6.1.0, and 6.0.0 on my
macOS version 10.13.6.  Only GMT 6.0.0 works. The more recent versions
show this error:
```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/GMT-6.1.0.app/Contents/Resources/bin/../lib/libcurl.4.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/GMT-6.1.0.app/Contents/Resources/bin/../lib/libcurl.4.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

The error indicates that 6.1.0 and 6.1.1 require a minimum macOS
version 10.15. GMT version 6.0.0 works fine on my macOS 10.13.6,
so I have updated the chart of minimum macOS requirements.