Attempt to prevent lint failures
Not sure if this will work.  Trying to get pass these:

src/gmt_init.c:13753:69: warning: Possible null pointer dereference: pen [nullPointer]
  if (outline && (S->v.status & PSL_VEC_OUTLINE2) == 0) S->v.pen = *pen; /* If no +p<pen> but -W<pen> was used, use same pen for vector heads */
                                                                    ^
src/gmt_init.c:14005:47: note: Calling function 'gmt_init_vector_param', 5th argument 'NULL' value is 0
 gmt_init_vector_param (GMT, S, false, false, NULL, false, NULL);
                                              ^
src/gmt_init.c:13752:6: note: Assuming condition is true.
 if (set) { /* Determine proper settings for head fill or outline */
     ^
src/gmt_init.c:13753:69: note: Null pointer dereference
  if (outline && (S->v.status & PSL_VEC_OUTLINE2) == 0) S->v.pen = *pen; /* If no +p<pen> but -W<pen> was used, use same pen for vector heads */
                                                                    ^
src/gmt_support.c:311:20: error: Array 'fill->pattern[1024]' accessed at index 9998, which is out of bounds. [arrayIndexOutOfBounds]
  if (fill->pattern[i] == ':' && i < len && (fill->pattern[i+1] == 'B' || fill->pattern[i+1] == 'F')) pos = i;
                   ^
src/gmt_support.c:10518:45: error: Array 'GMT->current.setting.format_float_map[64]' accessed at index 9998, which is out of bounds. [arrayIndexOutOfBounds]
   if (GMT->current.setting.format_float_map[i] == '.') j = i;
                                            ^
We will see what happens in the CI